version: '3.8'

services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2001:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
    volumes:
      - ./mlruns:/app/mlruns
    command: ["./start.sh"]
