channels:
- conda-forge
dependencies:
- python=3.10.10
- pip<=24.1
- pip:
  - mlflow==2.14.2
  - cloudpickle==3.0.0
  - logging==0.4.9.6
  - numpy==1.26.2
  - packaging==24.1
  - psutil==6.0.0
  - pyyaml==6.0.1
  - scikit-learn==1.4.2
  - scipy==1.14.0
name: mlflow-env
